### PR TITLE
Pusher fixes

### PR DESCRIPTION
**Pull request by zimbatm**
Hello from Pusher !

A couple of fixes in regards to the recent security issues. I couldn't find where the "socket_id" string was set on the client so the second commit is still failing. Feel free to cherry-pick to your likings.

### CODE REVIEW

**Comment by surfacedamage** [comment]
Hey, @zimbatm -- I cannot begin to tell you how cool it is that Pusher would take the time to close up security holes on third party libraries.

**Comment by esetera** [comment]
yes. @zimbatm thats a big thumbs up from me as well. Pusher earning good points in our camp. It means we know we can invest in slanger, and then have confidence that Pushers heart is in the right place should we decide for any reason to use their services. Awesome.

**Comment by zimbatm** [comment]
Thanks. I think slanger has it's place and there is room for more than one implementation out there. I can't really speak officially but I think that sentiment is shared inside the office. Go slanger ! :)

While on the subject, I have also pushed for our [HTTP](https://github.com/pusher/pusher-http-api-reference) and [WebSocket](https://github.com/pusher/pusher-socket-protocol) protocols documentations to be hosted in git repos. This should make them more easily diffable and hopefully help you guys when we're introducing changes. Also if you take a closer look you might or might not spot a new feature that we're working on ;)

**Comment by esetera** [comment]
:+1:

**Comment by markburns** [comment]
Nice thanks. I'd already made a start, but I'll pick some of this stuff. Closing because it's not passing the build.

**Comment by stevegraham** [comment]
Thanks @zimbatm ❤️

**Comment by markburns** [comment]
Thanks a lot, I pulled in some of this stuff in #186

**Pull request closed without merging**
