### PR TITLE
Update activesupport to 4.1 and update gem dependencies

### PR DESCRIPTION
**Pull request by mikechau**
activesupport 3.1 doesn't seem to place nice with ruby 2.2+, I've updated the dependencies to use activesupport 4.1.

To update to activesupport 4.2, it requires i18n 0.7, but glamazon still depends on 0.6.

#178

### CODE REVIEW

**Comment by markburns** [comment]
Actually, glamazon is only used in one place, and it's method_missing behaviour was hiding a bug. I have some changes that I might be merging in that remove glamazon

**Comment by stevegraham** [comment]
+1 removing glamazon. 5 years ago the method missing stuff seemed like a good idea.

**Comment by markburns** [comment]
@mikechau I'm in the middle of something else so can't do it right now, but
 if you want to get this PR merged in before I do the other stuff, here are the relevant changes: https://github.com/markburns/slanger/commit/364ea3e64fe9b4fb7c507e15edcd24fea9776acd

**Comment by mikechau** [comment]
@markburns I can do that, should I try upgrading activesupport to 4.2 as well?

**Comment by mikechau** [comment]
@markburns @stevegraham I removed glamazon and updated activesupport to 4.2

**Comment by markburns** [comment]
Nice, looks good to me, travis is happy. Would you mind adding ruby 2.2 to the travis config too, then if it still passes I think we can merge

**Comment by mikechau** [comment]
Ahh crap messed up the rebase. I'll do another PR.

**Pull request closed without merging**
