### PR TITLE
Improve performance of Slanger

### PR DESCRIPTION
**Pull request by doersf**
* Replace JSON loading/dumping with [Oj](https://github.com/ohler55/oj).
* Add ability to disable authentication -- increased performance under very high traffic loads.

### CODE REVIEW

**Comment by markburns** [comment]
No problem with the oj stuff looks like a good idea. Thanks. We can merge
that in easily as a separate pr if you want to get that in quickly.

I feel like the validation term is a misnomer as it is really disabling
authentication.

Also do you have any benchmarks for this?

**Comment by doersf** [comment]
No benchmark. We're pushing transactions at a roughly 10-15x the volume than just a week ago, and this showed up as a bottleneck. Will update the code and provide benchmarks in the next post.

**Comment by markburns** [comment]
I cherry picked your OJ changes. In master and released in v0.4.4.
Thanks!

I'm actually kind of curious about the disabling of auth. One thing I'd be wary of is setting a precedent for making it easy to create an insecure service. I'm particularly interested in the fact that you work for a bitcoin wallet service too.

I'm hoping that my curiosity is misplaced though and you have a valid secure use case and that you're not inadvertently flagging security holes up for everyone to see.

I'll close this PR. But feel free to reopen or open a new one.

**Comment by doersf** [comment]
Hey Mark, thanks for the merge.

Regarding authentication: to improve performance we lock down machines through firewalls to local machines that allowed to publish content through Slanger. If the existing behavior is indeed required by users, it can be done through faster hashes. 

For instance, Ruby's Signature gem uses the SHA256 hashing algorithm, which is much slower than MD5 (MD5 is around 3x faster than SHA256). The trade-off comes at the cost of the possibility of hash collisions in MD5. This, ofcourse, involves changing the Signature gem itself, maybe adding a mode for higher performance not enabled by default.

**Comment by stevegraham** [comment]
I don't think a patch to make authentication optional makes sense because it's highly specific to your use case.

**Comment by doersf** [comment]
Your call :) Cheers.

**Comment by markburns** [comment]
@doersf - a complete aside and I'm no security expert, but anywhere there's mention of trading off security and performance it always sets alarm bells ringing for me.
Are you sure that considering improving the performance of the hashing would be the right thing to do? 

E.g. in the linked file there is a constant time comparison to avoid timing attacks. I only glanced at the code, but what you are saying sounds a bit like a speed up based on the number of keys, which sounds like a timing attack vulnerability.

**Comment by doersf** [comment]
@markburns Performance of hashing -- yes. SHA256 vs. MD5: lower hash collisions in SHA256. It is simply a function that takes your data, and returns a large, seemingly _random_ integer for every small change in the input.

Regarding the timing attack: you'll have to elaborate on this. Have you come across a reliable timing attack on the MD5 algorithm itself? At the cost of going on a tangent: can you link the part with the constant time comparison?

[Related: On Timing Attacks](http://crypto.stackexchange.com/questions/25607/practical-uses-for-timing-attacks-on-hash-comparisons-e-g-md5)

**Comment by stevegraham** [comment]
https://github.com/mloughran/signature/blob/master/lib/signature.rb#L229

**Comment by doersf** [comment]
@stevegraham Ah, there it is. Now how does replacing SHA256 break this check?

**Comment by stevegraham** [comment]
MD5 has been considered cryptographically broken for about 5 years. As the point of a signature pertains to cryptography, what is your argument that MD5 is a suitable algo for signatures?

**Comment by doersf** [comment]
@stevegraham Indeed, but if fool-proof security is indeed what you're looking for, you'd want to use SHA512. In addition, you'd want to use salts to prevent rainbow table attacks. The list can go pretty deep here. The minimum you'd want: MD5 + specified minimum length of the secret.

In any case, even if you keep using SHA256 for signature verification, Slanger shouldn't be using the Signature gem if you've got performance in mind. All signs point to performance is not a major consideration here yet. I'll provide an FFI module as replacement in a future pull request once I can.

**Comment by stevegraham** [comment]
Slanger is just a Pusher implementation. Thanks for your suggestions but we're not diverging from that.

**Comment by doersf** [comment]
@stevegraham FFI isn't diverging from Pusher. I'm done.

**Comment by markburns** [comment]
I think getting performance improvements in that improve the signature gem
would be welcome and make sense.
I don't think doing anything along the lines of improving slanger
performance by changing the algorithm used is something that we would
consider (or would likely be considered for the signature gem).
Obviously if something gets accepted there we'd probably be glad to bump
the gem.
Thanks again for your contribution :)

**Pull request closed without merging**
