### PR TITLE
Allow more punctuation and a max of 164 characters in channel name

### LINKED ISSUE #189: Channel name should allow more punctuation and a max of 164 characters
As per Pusher's [documentation](https://pusher.com/docs/client_api_guide/client_channels#naming-channels):

> Channel names may contain a maximum of 164 characters. This limit includes channel prefixes (i.e. private- and presence- are included in the character count)

> Channel names should only include lower and uppercase letters, numbers and the following punctuation `_ - = @ , . ;`

### PR DESCRIPTION
**Pull request by rubenrails**
Fixes #189

### CODE REVIEW

**Comment by markburns** [comment]
Thanks

**Comment by rubenrails** [comment]
No problem, thanks for a fantastic library :)

**Comment by rubenrails** [comment]
Hey @markburns, could you bump the version to include this change? I appreciate your help :)

**Comment by markburns** [comment]
release 0.4.3

**Comment by rubenrails** [comment]
Awesome, thanks @markburns :)

**Pull request merged**
